{
 "title": "Orion",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status historiek",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT last(\"state\") AS \"state\"\nFROM \"orion_data\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "Kamer",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "orion_data",
     "query": "SELECT last(\"IMU\") AS \"kamer.IMU\"\nFROM \"orion_data\"\nWHERE \"device\" = 'kamer' AND $timeFilter\nGROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "device" ], "type": "field" }
      ],
      [
       { "params": [ "PIR" ], "type": "field" }
      ],
      [
       { "params": [ "IMU" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT last(\"PIR\") AS \"kamer.PIR\"\nFROM \"orion_data\"\nWHERE \"device\" = 'kamer' AND $timeFilter\nGROUP BY time($__interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "Toilet",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "orion_data",
     "query": "SELECT last(\"IMU\") AS \"toilet.IMU\"\nFROM \"orion_data\"\nWHERE \"device\" = 'toilet' AND $timeFilter\nGROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "device" ], "type": "field" }
      ],
      [
       { "params": [ "PIR" ], "type": "field" }
      ],
      [
       { "params": [ "IMU" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT last(\"PIR\") AS \"toilet.PIR\"\nFROM \"orion_data\"\nWHERE \"device\" = 'toilet' AND $timeFilter\nGROUP BY time($__interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "Bed",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "orion_data",
     "query": "SELECT last(\"IMU\") AS \"bed.IMU\"\nFROM \"orion_data\"\nWHERE \"device\" = 'bed' AND $timeFilter\nGROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "device" ], "type": "field" }
      ],
      [
       { "params": [ "PIR" ], "type": "field" }
      ],
      [
       { "params": [ "IMU" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT last(\"PIR\") AS \"bed.PIR\"\nFROM \"orion_data\"\nWHERE \"device\" = 'bed' AND $timeFilter\nGROUP BY time($__interval) fill(null)\n"
    },
    {
     "query": "SELECT last(\"LED\") AS \"bed.LED\"\nFROM \"orion_data\"\nWHERE \"device\" = 'bed' AND $timeFilter\nGROUP BY time($__interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "Raw data",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "SELECT * FROM \"orion_data\"\nWHERE $timeFilter"
    }
   ]
  }
 ]
}